# -*- coding: utf-8 -*-
"""UTCI Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J1jqg0xVVlohvVKeTU7Qb0w1NvaG1-qR
"""

!pip install --upgrade xee

!pip install -U geemap

import ee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

import geemap

map = geemap.Map()
map

roi = map.draw_last_feature.geometry()
roi

fldas = (
    ee.ImageCollection("NASA/FLDAS/NOAH01/C/GL/M/V001")
    .filterDate('2020','2021')
    .select(['Tair_f_tavg','Wind_f_tavg','Qair_f_tavg','RadT_tavg'],
            ['tas','sfcWind','hurs','mrt'])
    .map(
         lambda img: img.select('sfcWind','hurs').addBands(
             img.select('tas', 'mrt').subtract(273.15)
         )
    )
)

fldas

import xarray as xr

ds = xr.open_dataset(
    fldas,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.11,
    geometry = roi
)

ds = ds.sortby('time') * 1

ds.tas.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 6,
    robust = True
)

!pip install xclim

from xclim.indicators.convert import universal_thermal_climate_index

tas = ds.tas
tas.attrs['units'] = 'degC'
hurs = ds.hurs
hurs.attrs['units'] = ''
sfcWind = ds.sfcWind
sfcWind.attrs['units'] = 'm s-1'
mrt = ds.mrt
mrt.attrs['units'] = 'degC'

utci = universal_thermal_climate_index(
    tas = tas,
    hurs = hurs,
    sfcWind = sfcWind,
    mrt = mrt
)

utci_cel = utci - 273.15

utci_cel.plot(
    x = 'lon',
    y = 'lat',
    robust = True,
    col = 'time',
    col_wrap = 6
)